#include "ReportExport.h"

#include "AlertEngine.h"
#include "Diagnostics.h"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <sstream>

namespace aegis
{
    namespace
    {
        std::string Html(std::string value)
        {
            std::string out;
            out.reserve(value.size());
            for (const char c : value)
            {
                switch (c)
                {
                case '&': out += "&amp;"; break;
                case '<': out += "&lt;"; break;
                case '>': out += "&gt;"; break;
                case '"': out += "&quot;"; break;
                case '\'': out += "&#39;"; break;
                default: out.push_back(c); break;
                }
            }
            return out;
        }

        std::string Slug(std::string value)
        {
            value = Upper(Trim(value));
            std::string out;
            for (const unsigned char c : value)
            {
                if (std::isalnum(c))
                    out.push_back(static_cast<char>(c));
                else if (c == '.' || c == '-')
                    out.push_back('-');
            }
            return out.empty() ? "REPORT" : out;
        }

        void WriteStyle(std::ofstream& file)
        {
            file << "<style>";
            file << "body{margin:0;background:#f4f7f5;color:#10201b;font-family:Segoe UI,Arial,sans-serif;line-height:1.45}";
            file << "main{max-width:1180px;margin:0 auto;padding:28px}";
            file << "header{background:#081512;color:#effaf3;padding:28px;border-bottom:5px solid #36c36b}";
            file << "h1{margin:0;font-size:32px} h2{margin:28px 0 10px;font-size:20px} h3{margin:16px 0 8px;font-size:16px}";
            file << ".muted{color:#64746e}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}";
            file << ".metric{background:white;border:1px solid #dbe5df;border-radius:8px;padding:14px}.metric b{display:block;font-size:20px;margin-top:4px}";
            file << "table{border-collapse:collapse;width:100%;background:white;border:1px solid #dbe5df;margin:8px 0 18px}";
            file << "th,td{text-align:left;padding:8px 10px;border-bottom:1px solid #e4ece7;vertical-align:top}th{background:#eaf3ee;font-size:12px;text-transform:uppercase;letter-spacing:.04em}";
            file << ".pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#dff4e7;color:#0d5d2e;font-weight:600}.warn{background:#fff1d6;color:#754600}.risk{background:#ffe3e3;color:#8f1e1e}";
            file << ".section{margin-top:22px}.guard{background:#fff;border-left:5px solid #36c36b;padding:12px 14px;margin:14px 0}.small{font-size:12px}";
            file << "a{color:#0b6840}";
            file << "</style>";
        }

        void BeginDocument(std::ofstream& file, const std::string& title, const std::string& subtitle)
        {
            file << "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">";
            file << "<title>" << Html(title) << "</title>";
            WriteStyle(file);
            file << "</head><body><header><h1>" << Html(title) << "</h1><div class=\"muted\">" << Html(subtitle) << "</div></header><main>";
            file << "<div class=\"guard\"><b>Research only.</b> This report organizes local/provider data for paper research. It is not investment advice and does not place orders.</div>";
        }

        void EndDocument(std::ofstream& file)
        {
            file << "<p class=\"muted small\">Generated by Auralith Research Cockpit. API keys and credentials are not written to reports.</p>";
            file << "</main></body></html>";
        }

        void Metric(std::ofstream& file, const std::string& name, const std::string& value, const std::string& detail = {})
        {
            file << "<div class=\"metric\"><span class=\"muted\">" << Html(name) << "</span><b>" << Html(value) << "</b>";
            if (!detail.empty())
                file << "<div class=\"small\">" << Html(detail) << "</div>";
            file << "</div>";
        }

        void InfoTable(std::ofstream& file, const std::string& title, const std::vector<InfoItem>& rows)
        {
            file << "<section class=\"section\"><h2>" << Html(title) << "</h2>";
            if (rows.empty())
            {
                file << "<p class=\"muted\">No rows.</p></section>";
                return;
            }
            file << "<table><thead><tr><th>Name</th><th>State</th><th>Value</th><th>Detail</th><th>Source</th></tr></thead><tbody>";
            for (const InfoItem& row : rows)
            {
                file << "<tr><td>" << Html(row.name) << "</td><td>" << Html(!row.label.empty() ? row.label : (!row.state.empty() ? row.state : row.tag)) << "</td><td>" << Html(row.value) << "</td><td>" << Html(row.detail) << "</td><td>" << Html(row.source) << "</td></tr>";
            }
            file << "</tbody></table></section>";
        }

        void LinkList(std::ofstream& file, const std::string& title, const std::vector<FilingItem>& rows)
        {
            file << "<section class=\"section\"><h2>" << Html(title) << "</h2><table><thead><tr><th>Form</th><th>Date</th><th>Summary</th><th>Risk</th><th>Link</th></tr></thead><tbody>";
            for (const FilingItem& row : rows)
            {
                file << "<tr><td>" << Html(row.form) << "</td><td>" << Html(row.date) << "</td><td>" << Html(row.summary) << "</td><td>" << Html(row.risk_change) << "</td><td>";
                if (!row.url.empty())
                    file << "<a href=\"" << Html(row.url) << "\">Open</a>";
                file << "</td></tr>";
            }
            file << "</tbody></table></section>";
        }

        void NewsTable(std::ofstream& file, const std::vector<NewsItem>& rows)
        {
            file << "<section class=\"section\"><h2>News</h2><table><thead><tr><th>Date</th><th>Source</th><th>Sentiment</th><th>Headline</th></tr></thead><tbody>";
            for (const NewsItem& row : rows)
            {
                file << "<tr><td>" << Html(row.date) << "</td><td>" << Html(row.source) << "</td><td>" << Html(row.sentiment) << "</td><td>";
                if (!row.url.empty())
                    file << "<a href=\"" << Html(row.url) << "\">" << Html(row.title) << "</a>";
                else
                    file << Html(row.title);
                file << "<div class=\"small\">" << Html(row.summary) << "</div></td></tr>";
            }
            file << "</tbody></table></section>";
        }

        void EarningsTable(std::ofstream& file, const std::vector<EarningsItem>& rows)
        {
            file << "<section class=\"section\"><h2>Earnings</h2><table><thead><tr><th>Date</th><th>Status</th><th>Estimate</th><th>Actual</th><th>Surprise</th><th>Move/Drift</th></tr></thead><tbody>";
            for (const EarningsItem& row : rows)
            {
                file << "<tr><td>" << Html(row.date) << "</td><td>" << Html(row.status) << "</td><td>" << Html(FormatCurrency(row.eps_estimate)) << "</td><td>" << Html(row.eps_actual > 0.0 ? FormatCurrency(row.eps_actual) : "--") << "</td><td>" << Html(FormatPercent(row.surprise)) << "</td><td>" << Html(FormatPercent(row.estimated_move) + " / " + FormatPercent(row.drift)) << "</td></tr>";
            }
            file << "</tbody></table></section>";
        }
    }

    std::filesystem::path ReportsDirectory()
    {
        std::filesystem::path path = AppDataDirectory() / "reports";
        std::error_code ec;
        std::filesystem::create_directories(path, ec);
        return path;
    }

    bool ExportSymbolResearchReport(const SymbolResearchReport& report, std::filesystem::path& output_path, std::string& status)
    {
        output_path = ReportsDirectory() / (Slug(report.quote.symbol) + "-research-report.html");
        std::ofstream file(output_path, std::ios::trunc);
        if (!file)
        {
            status = "Could not write research report.";
            return false;
        }

        BeginDocument(file, report.quote.symbol + " Research Report", report.quote.name + " | generated " + NowTimeLabel());
        file << "<div class=\"grid\">";
        Metric(file, "Price", FormatCurrency(report.quote.price), report.quote.latest_trading_day);
        Metric(file, "Change", FormatPercent(report.quote.change_percent), report.quote.source);
        Metric(file, "Signal", report.signal.rating, report.signal.posture);
        Metric(file, "Score", std::to_string(report.signal.score), std::to_string(report.signal.confidence) + "% confidence");
        Metric(file, "Target", FormatCurrency(report.signal.target_price), "Stop " + FormatCurrency(report.signal.stop_level));
        Metric(file, "Volume", FormatVolume(report.quote.volume), report.quote.status);
        file << "</div>";
        file << "<section class=\"section\"><h2>Thesis</h2><p>" << Html(report.signal.thesis) << "</p></section>";
        file << "<section class=\"section\"><h2>Freshness</h2><table><tbody>";
        file << "<tr><th>History</th><td>" << Html(report.history_source) << "</td><td>" << Html(report.history_freshness) << "</td><td>" << Html(report.history_fallback) << "</td></tr>";
        file << "<tr><th>Research</th><td>" << Html(report.research_source) << "</td><td>" << Html(report.research_freshness) << "</td><td>" << Html(report.research_fallback) << "</td></tr>";
        file << "</tbody></table></section>";
        file << "<section class=\"section\"><h2>Technical Snapshot</h2><div class=\"grid\">";
        Metric(file, "Regime", report.indicators.regime);
        Metric(file, "SMA 20 / 50", FormatCurrency(report.indicators.sma20) + " / " + FormatCurrency(report.indicators.sma50));
        Metric(file, "RSI 14", FormatPercent(report.indicators.rsi14));
        Metric(file, "MACD", FormatCurrency(report.indicators.macd) + " / " + FormatCurrency(report.indicators.macd_signal));
        Metric(file, "ATR 14", FormatCurrency(report.indicators.atr14));
        Metric(file, "Drawdown", FormatPercent(report.indicators.drawdown));
        file << "</div></section>";
        InfoTable(file, "Explainable Score", report.explanation);
        InfoTable(file, "Trade Checklist", report.checklist);
        InfoTable(file, "Risk Critic", report.risk_critic);
        InfoTable(file, "Backtest", report.backtest.rows);
        if (!report.strategy_rule.empty())
        {
            file << "<section class=\"section\"><h2>Strategy Builder</h2><p><b>Rule:</b> " << Html(report.strategy_rule) << "</p><p>" << Html(report.strategy_status) << "</p></section>";
            InfoTable(file, "Strategy Backtest", report.strategy_backtest.rows);
        }
        file << "<section class=\"section\"><h2>Fundamentals</h2><div class=\"grid\">";
        Metric(file, "Revenue", FormatCompactCurrency(report.fundamentals.revenue));
        Metric(file, "EPS", FormatCurrency(report.fundamentals.eps));
        Metric(file, "Margins", FormatPercent(report.fundamentals.gross_margin) + " / " + FormatPercent(report.fundamentals.net_margin));
        Metric(file, "Debt/Equity", FormatPercent(report.fundamentals.debt_to_equity));
        Metric(file, "Free cash flow", FormatCompactCurrency(report.fundamentals.free_cash_flow));
        Metric(file, "P/E / PEG", FormatPercent(report.fundamentals.pe) + " / " + FormatPercent(report.fundamentals.peg));
        file << "</div><p>" << Html(report.fundamentals.summary) << "</p></section>";
        LinkList(file, "SEC Filings", report.filings);
        NewsTable(file, report.news);
        EarningsTable(file, report.earnings);
        EndDocument(file);

        status = "Research report exported: " + output_path.string();
        AppendDiagnosticEvent({ "info", "report", "symbol", report.quote.symbol, "exported", output_path.string(), "", 0, 0, false });
        return true;
    }

    bool ExportDailyBriefingReport(const DailyBriefingReport& report, std::filesystem::path& output_path, std::string& status)
    {
        output_path = ReportsDirectory() / "today-briefing.html";
        std::ofstream file(output_path, std::ios::trunc);
        if (!file)
        {
            status = "Could not write daily briefing.";
            return false;
        }

        BeginDocument(file, "Auralith Today's Briefing", report.state.source_badge + " | generated " + NowTimeLabel());
        InfoTable(file, "Dashboard Metrics", report.state.metrics);
        InfoTable(file, "Research State", report.state.research);
        file << "<section class=\"section\"><h2>Top Signals</h2><table><thead><tr><th>Symbol</th><th>Rating</th><th>Score</th><th>Risk</th><th>Thesis</th></tr></thead><tbody>";
        const int signal_limit = std::min(12, static_cast<int>(report.state.signals.size()));
        for (int i = 0; i < signal_limit; ++i)
        {
            const StockSignal& signal = report.state.signals[static_cast<size_t>(i)];
            file << "<tr><td>" << Html(signal.symbol) << "</td><td>" << Html(signal.rating) << "</td><td>" << signal.score << "</td><td>" << Html(signal.risk) << "</td><td>" << Html(signal.thesis) << "</td></tr>";
        }
        file << "</tbody></table></section>";
        file << "<section class=\"section\"><h2>Today's Focus</h2><table><thead><tr><th>Symbol</th><th>Priority</th><th>Reason</th><th>Detail</th></tr></thead><tbody>";
        for (const FocusItem& item : report.focus)
            file << "<tr><td>" << Html(item.symbol) << "</td><td>" << Html(item.priority) << "</td><td>" << Html(item.reason) << "</td><td>" << Html(item.detail) << "</td></tr>";
        file << "</tbody></table></section>";
        file << "<section class=\"section\"><h2>Alert Events</h2><table><thead><tr><th>Symbol</th><th>State</th><th>Observed</th><th>Triggered</th><th>Note</th></tr></thead><tbody>";
        int events_written = 0;
        for (auto it = report.alert_events.rbegin(); it != report.alert_events.rend() && events_written < 15; ++it, ++events_written)
            file << "<tr><td>" << Html(it->symbol) << "</td><td>" << Html(AlertEventState(*it)) << "</td><td>" << Html(FormatCurrency(it->observed_price)) << "</td><td>" << Html(it->triggered_at) << "</td><td>" << Html(it->note) << "</td></tr>";
        file << "</tbody></table></section>";
        file << "<section class=\"section\"><h2>Holdings</h2><table><thead><tr><th>Symbol</th><th>Shares</th><th>Average Cost</th><th>Note</th></tr></thead><tbody>";
        for (const PortfolioHolding& holding : report.holdings)
            file << "<tr><td>" << Html(holding.symbol) << "</td><td>" << holding.shares << "</td><td>" << Html(FormatCurrency(holding.average_cost)) << "</td><td>" << Html(holding.note) << "</td></tr>";
        file << "</tbody></table></section>";
        EndDocument(file);

        status = "Daily briefing exported: " + output_path.string();
        AppendDiagnosticEvent({ "info", "report", "briefing", "", "exported", output_path.string(), "", 0, 0, false });
        return true;
    }
}
